version: '3.7'
services:
  haproxy:
    network_mode: host
    image: haproxy:2.1.2
    ports:
      - 8085:8085
    ulimits:
      nproc: 65535
      nofile:
        soft: 200000
        hard: 200000
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
